-- Ejecutar este script en Oracle como SYSTEM o un usuario nuevo
CREATE TABLE PRODUCTOS (
    ID_PRODUCTO NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NOMBRE VARCHAR2(100) NOT NULL,
    PRECIO NUMBER(10, 2) NOT NULL,
    CANTIDAD NUMBER NOT NULL,
    CATEGORIA VARCHAR2(50)
);

-- Datos de prueba opcionales
INSERT INTO PRODUCTOS (NOMBRE, PRECIO, CANTIDAD, CATEGORIA) VALUES ('Monitor', 3500.00, 2, 'Electronica');
COMMIT;